"""
Gospel / anti-gospel lexicons for EN + Nigerian Pidgin + Yoruba / Igbo / Hausa.
Used for deterministic text scoring without cloud AI.
"""
from __future__ import annotations

# Strong Christian / gospel signals
GOSPEL_TERMS: list[str] = [
    # English
    "jesus",
    "christ",
    "gospel",
    "bible",
    "scripture",
    "worship",
    "hallelujah",
    "hosanna",
    "sermon",
    "pastor",
    "holy spirit",
    "kingdom of god",
    "word of god",
    "prayer",
    "amen",
    "salvation",
    "redemption",
    "repentance",
    "grace",
    "covenant",
    "righteousness",
    "resurrection",
    "born again",
    "sanctification",
    "disciple",
    "apostle",
    "testimony",
    "congregation",
    "altar",
    "cross",
    "crucified",
    "risen",
    "eternal life",
    "kingdom of heaven",
    "praise",
    "hymn",
    "choir",
    "ministry",
    "evangelism",
    "fellowship",
    "anointing",
    "blood of jesus",
    "lamb of god",
    "messiah",
    "yahweh",
    "jehovah",
    "psalm",
    "proverb",
    "genesis",
    "romans",
    "isaiah",
    "matthew",
    "john",
    "paul the apostle",
    # Yoruba
    "oluwa",
    "olorun",
    "jesu",
    "yesu",
    "adura",
    "igbagbo",
    "orin iyin",
    "olorun tobi",
    # Igbo
    "chukwu",
    "chineke",
    "jisos",
    "ekpere",
    "otito",
    # Hausa
    "ubangiji",
    "addu'a",
    "ibada",
    # Pidgin gospel
    "god dey",
    "jesus dey",
    "thank god",
    "bless god",
    "holy ghost",
    "fire of god",
]

# Secular / club / sexual / anti-gospel themes (scoring — hard blocklist still in Node)
ANTI_GOSPEL_TERMS: list[str] = [
    "porn",
    "porno",
    "xxx",
    "nude",
    "nudity",
    "strip club",
    "nightclub",
    "club banger",
    "onlyfans",
    "ashawo",
    "olosho",
    "oloshi",
    "runs girl",
    "runsgirl",
    "doggy style",
    "quickie",
    "masturbat",
    "knack me",
    "i go knack",
    "come knack",
    "tap that",
    "tap current",
    "blaspheme",
    "blasphemy",
    "satanic ritual",
    "witchcraft party",
    "secular rap",
    "trap music",
    "afrobeats party",
    "club vibe",
    "turn up",
    "flexing money",
    "lewd dance",
    "twerk",
    "grinding on",
]

# Soft secular entertainment cues (lower weight)
SECULAR_SOFT_TERMS: list[str] = [
    "party vibes",
    "dance challenge",
    "tiktok dance",
    "club night",
    "rave",
    "hookup",
    "side chick",
    "side chic",
    "sugar daddy",
    "yahoo boy",
]
