"""
Tiered gospel lexicons for EN + Nigerian Pidgin + Yoruba / Igbo / Hausa.

ANCHOR — clear Christian / biblical body signal (Jesus, God, Scripture, gospel theology).
SUPPORT — worship / hymn / choir language that strengthens an anchor.
ATMOSPHERE — prayer / amen / pastor / ministry (counts toward score with anchors/support).
"""
from __future__ import annotations

# Jesus / Christ names (EN + local forms)
JESUS_NAME_TERMS: list[str] = [
    "jesus",
    "christ",
    "jesu",
    "yesu",
    "jisos",
    "messiah",
    "jesu kristi",
    "jesus dey",
    "blood of jesus",
    "lamb of god",
    "in jesus name",
]

# Any clear Christian / biblical body signal — enough to auto-publish when safe
GOSPEL_ANCHOR_TERMS: list[str] = JESUS_NAME_TERMS + [
    "yahweh",
    "jehovah",
    "holy spirit",
    "holy ghost",
    "almighty god",
    "living god",
    "our god",
    "praise god",
    "praise the god",
    "glory to god",
    "thank god",
    "thank you god",
    "bless god",
    "blessed be god",
    "bible",
    "scripture",
    "word of god",
    "kingdom of god",
    "kingdom of heaven",
    "son of god",
    "salvation",
    "redemption",
    "repentance",
    "repent",
    "resurrection",
    "crucified",
    "risen",
    "born again",
    "sanctification",
    "eternal life",
    "everlasting life",
    "only begotten",
    "whosoever believeth",
    "whosoever believes",
    "for god so loved",
    "gospel",
    "the lord",
    "heavenly father",
    "father in heaven",
    "open your bible",
    "open your bibles",
    "turn with me to",
    "brothers and sisters",
    "brother and sister",
    "beloved brethren",
    "holy bible",
    "reading from the word",
    "reading from scripture",
    "reading from the bible",
    "oluwa",
    "olorun",
    "chukwu",
    "chineke",
    "ubangiji",
    "god dey do",
    "god dey",
]

# Worship / hymn language — confirms Christian content
GOSPEL_SUPPORT_TERMS: list[str] = [
    "worship",
    "hallelujah",
    "halleluyah",
    "hosanna",
    "hymn",
    "choir",
    "testimony",
    "evangelism",
    "anointing",
    "orin iyin",
    "olorun tobi",
    "igbagbo",
    "otito",
    "ibada",
    "thank god",
    "bless god",
    "fire of god",
    "amazing grace",
    "how great thou art",
    "blessed assurance",
    "to god be the glory",
    "great is thy faithfulness",
    "praise and worship",
]

# Quiet sermons and prayer language
GOSPEL_ATMOSPHERE_TERMS: list[str] = [
    "prayer",
    "amen",
    "pastor",
    "ministry",
    "grace",
    "sermon",
    "congregation",
    "altar",
    "praise",
    "fellowship",
    "disciple",
    "apostle",
    "covenant",
    "righteousness",
    "adura",
    "ekpere",
    "addu'a",
    "let us pray",
    "make we pray",
    "make una pray",
]

# Backward-compatible union
GOSPEL_TERMS: list[str] = (
    GOSPEL_ANCHOR_TERMS + GOSPEL_SUPPORT_TERMS + GOSPEL_ATMOSPHERE_TERMS
)

ANTI_GOSPEL_TERMS: list[str] = [
    "porn",
    "porno",
    "xxx",
    "nude",
    "nudity",
    "strip club",
    "nightclub",
    "club banger",
    "onlyfans",
    "ashawo",
    "olosho",
    "oloshi",
    "runs girl",
    "runsgirl",
    "doggy style",
    "quickie",
    "masturbat",
    "knack me",
    "i go knack",
    "come knack",
    "tap that",
    "tap current",
    "blaspheme",
    "blasphemy",
    "satanic ritual",
    "witchcraft party",
    "secular rap",
    "trap music",
    "afrobeats party",
    "club vibe",
    "turn up",
    "flexing money",
    "lewd dance",
    "twerk",
    "grinding on",
    "chop babe",
    "chopping babe",
    "side chick",
    "side chic",
    "in my dm",
    "in my dms",
    "slide in my dm",
    "full in my dm",
    "send nudes",
    "hookup",
    "one night stand",
]

SECULAR_SOFT_TERMS: list[str] = [
    "party vibes",
    "dance challenge",
    "tiktok dance",
    "club night",
    "rave",
    "hookup",
    "side chick",
    "side chic",
    "sugar daddy",
    "yahoo boy",
    "my babe",
    "fine girl",
    "fine babe",
    "dm me",
    "in my dm",
]

# Generic motivation / self-help (reject when no gospel anchor)
MOTIVATION_TERMS: list[str] = [
    "motivational speaker",
    "motivation monday",
    "mindset",
    "hustle culture",
    "law of attraction",
    "manifestation",
    "self help",
    "self-help",
    "believe in yourself",
    "grind mode",
    "passive income",
    "millionaire mindset",
    "boss babe",
    "success tips",
    "confidence tips",
    "how to get rich",
    "level up your life",
]
