version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/jevah
      - JWT_SECRET=your-development-jwt-secret
      - RESEND_API_KEY=your-resend-api-key
      - FRONTEND_URL=http://localhost:3000
      - LOG_LEVEL=debug
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - jevah-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=jevah
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - jevah-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - jevah-network

volumes:
  mongo_data:

networks:
  jevah-network:
    driver: bridge
